### ISSUE TITLE
Review comments for emissions categories and fuels is not working properly

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-ciip-portal#2128] opened 2022-12-16 17:23 UTC
#### Describe the task
Application has a fuel reported for every emission category where an emission was reported. 

Errors are hidden/application is correct which meant that applicants reach out to CIIP team for clarification which has become annoying for the CIIP team. Some investigation will be required to figure out what is going on. 
We may be able to do this without creating the UI, but that is upon further exploration.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by dleard** [comment] 2022-12-16 18:39
duplicate of #2125

**Closed by dleard** 2022-12-16 18:39 UTC
Labels: duplicate, enhancement, Backlog Refinement, Task
